{% set name = "mgrs" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ac7a06071c732c04052d6114150496633e2408638813ea17f9e053f4074146d

build:
  number: 0
  skip: True  # [win and vc<14]
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - setuptools
    - wheel

test:
  imports:
    - mgrs

about:
  home: https://github.com/hobu/mgrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'MGRS coordinate conversion for Python'
  dev_url: https://github.com/hobu/mgrs

extra:
  recipe-maintainers:
    - benhuff
    - oblute
    - rluria14
