travis:
  secure:
    BINSTAR_TOKEN: kFD3o1nRx1r6RoofhIlmbm0k0UWN11S6wjqshJHoAjhlv5UZiz3pZYkt1zHj6MzvPPBunF063Gx5y/fB2oeKR24Wa36SwXUKnm0d7zUojGxFERuZtruQxPSfwLDTfYUCN7heek7XGY07hJT++TS+ZlSBU84VA4ilkUVVVGLpi1jDVh/7oTywzkeb/eKQZoy+Xm4jPUqRkM8TtNgpqGwVV810UrzNqSWHfaUSN34EG46d2VD8YYyp3qMlaszYFvwShjF5Q+bRFkaOZkrjNiWAvdUa6dacPwcNpMTsefwn5YJv4R4vpnHU4iEAGjhy/tK+2Oc3AhvbGRqlhzC4Bx5CrDFRapiFOBC8afzQYnq/KCtm6WXVS/V21QrfjAwWJA8nF2mwn4X8WeRktRzuVP8Ura0cY8OAwIbRhfDYBwvzQGqOp8qBIHGQusQFqg4sPxjHOefyccdzKB5Fd/g/ctJ+LslZQl/gan7kedNeVgIZjhaGoZ8HkXcvRwoXQi/vilKmYsZgSzgvUjwBtQjHCBF4MlDYVmaXGS3sfE2Szy/YWOTiOSm3rmdPvAIO9saHkUbj6oFN6hvPPBaa5jcqKFLfU4mlZl+E4RztDHdaFJt6a6evlevynBU/W08Uhmx3qMumXTLhSQR7CoLUc7Usje47vJro3Hovx1iFsC6signC4p4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
